OPENQASM 3.0;
include "stdgates.inc";
qubit[6] q;
bit[3] c;
h q[3];
h q[4];
h q[5];
h q[5]; ccx q[3], q[4], q[5]; h q[5];
cx q[0], q[3];
cx q[1], q[4];
cx q[2], q[5];
c[0] = measure q[3];
c[1] = measure q[4];
c[2] = measure q[5];
if (c[0] == true) cz q[1], q[2];
if (c[1] == true) cz q[0], q[2];
if (c[2] == true) cz q[0], q[1];
if (c[0] == true) if (c[1] == true) z q[2];
if (c[0] == true) if (c[2] == true) z q[1];
if (c[1] == true) if (c[2] == true) z q[0];
