
-- Re-export shim: split into ToyWindow2Case3StateEquality/ submodules (same namespace; opens de-duplicated); importers unchanged.
import FormalRV.Shor.VerifiedShor.ToyWindow2Case3StateEquality.ArithmeticSpecsAndInterfaces
import FormalRV.Shor.VerifiedShor.ToyWindow2Case3StateEquality.CasesV1V2AndComposedGate
import FormalRV.Shor.VerifiedShor.ToyWindow2Case3StateEquality.WindowBitPreservation
import FormalRV.Shor.VerifiedShor.ToyWindow2Case3StateEquality.WorkspaceAndBitExtraction
import FormalRV.Shor.VerifiedShor.ToyWindow2Case3StateEquality.AboveLayoutHelper
