
-- Re-export shim: split into WindowedLoaderBitExtraction/ submodules (same namespace; opens de-duplicated); importers unchanged.
import FormalRV.Shor.VerifiedShor.WindowedLoaderBitExtraction.ShiftedLayoutDisjointness
import FormalRV.Shor.VerifiedShor.WindowedLoaderBitExtraction.ParametricSelectedAddFrame
import FormalRV.Shor.VerifiedShor.WindowedLoaderBitExtraction.StateBuilderReconstruction
import FormalRV.Shor.VerifiedShor.WindowedLoaderBitExtraction.PerWindowSelectedAddFrame
import FormalRV.Shor.VerifiedShor.WindowedLoaderBitExtraction.MultiWindowSelectedAdd
