
-- Re-export shim: split into WindowedSwapLoaderWithDataClear/ submodules (same namespace; opens de-duplicated); importers unchanged.
import FormalRV.Shor.VerifiedShor.WindowedSwapLoaderWithDataClear.MultiWindowFoldCorrect
import FormalRV.Shor.VerifiedShor.WindowedSwapLoaderWithDataClear.LoaderAdapterBitExtraction
import FormalRV.Shor.VerifiedShor.WindowedSwapLoaderWithDataClear.LoadedStateEncoding
import FormalRV.Shor.VerifiedShor.WindowedSwapLoaderWithDataClear.SourceIndexArithmetic
