/-
  FormalRV\QEC\Codes\LiftedProduct\LPTinyBasisImport.lean — GENERATED by scripts/find_logicals.py (UNTRUSTED external
  GF(2) solver).  Vectors are stored as Nat bitset hex literals and decoded
  by `FormalRV.QEC.bitsToVec` (lossless; ≈27× slimmer than Bool-list
  literals).  Lean verifies ONLY the cheap certificate below
  (`LogicalBasis.valid`: in-kernel + symplectic delta-pairing on the DECODED
  vectors, pure dot products — no Gaussian elimination, and no trust in the
  encoding); genuineness (outside the stabilizer rowspace) follows
  parametrically from `LogicalGenuine.valid_basis_genuine`.
  Regenerate: see the script header.  Do not edit by hand.
-/
import FormalRV.QEC.Logical
import FormalRV.QEC.Instances
import FormalRV.QEC.BasisCodec

-- kernel recursion headroom for `decide` over width-15 vectors
set_option maxRecDepth 2000000

namespace FormalRV.QEC.Codes.LP

open FormalRV.QEC

/-- Imported logical-Z bitsets (3 logical qubits), found externally. -/
def lpTinyImported_lzBits : List Nat :=
  [0x44,
   0x81,
   0x102]

/-- Imported logical-X bitsets, externally re-paired to the delta pairing. -/
def lpTinyImported_lxBits : List Nat :=
  [0xc,
   0x11,
   0x22]

def lpTinyImported_lz : List FormalRV.Framework.LDPC.BoolVec :=
  lpTinyImported_lzBits.map (bitsToVec 15)

def lpTinyImported_lx : List FormalRV.Framework.LDPC.BoolVec :=
  lpTinyImported_lxBits.map (bitsToVec 15)

/-- The imported PAIRED basis (naive sequential indexing: logical `i` is the
    `i`-th basis vector — the audit convention). -/
def lpTinyImportedBasis : LogicalBasis FormalRV.QEC.Algebraic.lpTiny 3 :=
  ⟨fun i => lpTinyImported_lx.getD i.val [], fun i => lpTinyImported_lz.getD i.val []⟩

end FormalRV.QEC.Codes.LP
