# Auto-generated by ls_compile.py — ray-traced lattice-surgery render.
# Run:  blender --background --python THIS_FILE      (or: python THIS_FILE  with the `bpy` module)
import bpy
from mathutils import Vector
BOXES = [
    (0.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (0.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (0.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (1.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (1.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (1.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (2.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (2.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (2.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (3.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (3.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (3.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (4.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (4.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (4.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (5.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (5.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (5.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (6.000,8.500,0.000, 0.340,17.000,0.340, 0.933,0.945,0.961, 0.40, 'wire'),
    (6.000,0.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (6.000,17.000,0.000, 0.500,0.500,0.500, 0.184,0.667,0.333, 1.00, 'port'),
    (1.500,1.000,0.000, 1.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (0.500,2.000,0.000, 1.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (1.000,3.000,0.000, 2.340,0.340,0.340, 0.886,0.282,0.227, 1.00, 'ccx'),
    (1.000,3.000,1.100, 0.500,0.500,0.500, 0.965,0.788,0.271, 1.00, 'factory'),
    (3.500,1.000,0.000, 1.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (2.000,4.000,0.000, 2.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (2.500,5.000,0.000, 3.340,0.340,0.340, 0.886,0.282,0.227, 1.00, 'ccx'),
    (2.500,5.000,1.100, 0.500,0.500,0.500, 0.965,0.788,0.271, 1.00, 'factory'),
    (5.500,1.000,0.000, 1.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (4.000,6.000,0.000, 2.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (4.500,7.000,0.000, 3.340,0.340,0.340, 0.886,0.282,0.227, 1.00, 'ccx'),
    (4.500,7.000,1.100, 0.500,0.500,0.500, 0.965,0.788,0.271, 1.00, 'factory'),
    (4.500,8.000,0.000, 3.340,0.340,0.340, 0.886,0.282,0.227, 1.00, 'ccx'),
    (4.500,8.000,1.100, 0.500,0.500,0.500, 0.965,0.788,0.271, 1.00, 'factory'),
    (4.000,9.000,0.000, 2.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (4.500,10.000,0.000, 3.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (2.500,11.000,0.000, 3.340,0.340,0.340, 0.886,0.282,0.227, 1.00, 'ccx'),
    (2.500,11.000,1.100, 0.500,0.500,0.500, 0.965,0.788,0.271, 1.00, 'factory'),
    (2.000,12.000,0.000, 2.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (2.500,13.000,0.000, 3.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (1.000,14.000,0.000, 2.340,0.340,0.340, 0.886,0.282,0.227, 1.00, 'ccx'),
    (1.000,14.000,1.100, 0.500,0.500,0.500, 0.965,0.788,0.271, 1.00, 'factory'),
    (0.500,15.000,0.000, 1.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx'),
    (1.000,16.000,0.000, 2.340,0.340,0.340, 0.231,0.435,0.831, 1.00, 'cx')
  ]
PNG = r"C:/Users/yezhu/Documents/FormalRV/docs/diagrams/ls_adder3_blender.png"
sc = bpy.context.scene
# clear
bpy.ops.object.select_all(action="SELECT"); bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
cache = {}
def get_mat(rgba):
    k = tuple(round(c, 3) for c in rgba)
    if k in cache: return cache[k]
    m = bpy.data.materials.new("m"); m.use_nodes = True
    b = m.node_tree.nodes.get("Principled BSDF")
    if b:
        b.inputs["Base Color"].default_value = (rgba[0], rgba[1], rgba[2], 1.0)
        if "Roughness" in b.inputs: b.inputs["Roughness"].default_value = 0.45
        if "Metallic" in b.inputs: b.inputs["Metallic"].default_value = 0.0
        if "Alpha" in b.inputs: b.inputs["Alpha"].default_value = rgba[3]
    cache[k] = m; return m
for cx, cy, cz, sx, sy, sz, r, g, bb, a, kind in BOXES:
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(cx, cy, cz))
    o = bpy.context.object; o.scale = (sx, sy, sz)
    o.data.materials.append(get_mat((r, g, bb, a)))
    bpy.ops.object.shade_flat()
xs = [b[0] for b in BOXES]; ys = [b[1] for b in BOXES]; zs = [b[2] for b in BOXES]
cen = Vector(((min(xs)+max(xs))/2, (min(ys)+max(ys))/2, (min(zs)+max(zs))/2))
ext = max(max(xs)-min(xs), max(ys)-min(ys), max(zs)-min(zs), 2.0)
bpy.ops.object.empty_add(location=cen); tgt = bpy.context.object
bpy.ops.object.camera_add(location=cen + Vector((ext*1.15, -ext*1.7, ext*1.0)))
cam = bpy.context.object; sc.camera = cam
con = cam.constraints.new("TRACK_TO"); con.target = tgt
con.track_axis = "TRACK_NEGATIVE_Z"; con.up_axis = "UP_Y"
bpy.ops.object.light_add(type="SUN", location=cen + Vector((ext, -ext, ext*2.5)))
bpy.context.object.data.energy = 3.5
bpy.ops.object.light_add(type="AREA", location=cen + Vector((-ext, -ext*0.5, ext*1.5)))
bpy.context.object.data.energy = 400.0; bpy.context.object.data.size = ext
w = bpy.data.worlds[0]; w.use_nodes = True
bg = w.node_tree.nodes.get("Background")
if bg: bg.inputs[0].default_value = (0.04, 0.05, 0.07, 1.0)
sc.render.engine = "CYCLES"
try: sc.cycles.samples = 40
except Exception: pass
sc.render.resolution_x = 1300; sc.render.resolution_y = 950
sc.render.filepath = PNG
bpy.ops.render.render(write_still=True)
print("rendered ->", PNG)
