"""Tests for the shared DEVICE-PROGRAM 1.0 loader (Lean <-> VM interop).

The adder_d3 example files are generated by
``lake env lean --run scripts/EmitAdderDeviceProgram.lean`` from the SAME
schedule objects certified in Lean (``schedule_fits`` /
``bad_parallel_adder_schedule_rejected``); these tests pin the VM half of
the cross-checker contract: named gates (gate=CNOT), explicit-qubit ancilla
requests (request_ancilla q[100]), and parallel-layer recognition.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from ftq_vm.backend.device_program import (DeviceProgramError,
                                           load_device_program,
                                           max_simultaneous, parallel_groups)
from ftq_vm.backend.loader import LoadError, load_backend, load_program
from ftq_vm.backend.simulator import run_simulation

EXAMPLES = Path(__file__).parent.parent / "examples"


def backend():
    return load_backend(EXAMPLES / "adder_d3_backend.json")


HEADER = "DEVICE-PROGRAM 1.0;\n// test program\n"


# --------------------------------------------------------------------------
# Grammar / lowering: named gates, explicit qubits
# --------------------------------------------------------------------------


def test_parses_all_op_forms_with_named_gates():
    text = HEADER + "\n".join([
        "[0,1)us  SYS   request_ancilla    q[100]",
        "[1,2)us  PHYS  gate2q             q[0],q[100] gate=CNOT",
        "[2,3)us  PHYS  gate1q             q[0] gate=H",
        "[3,4)us  PHYS  measure            q[100] basis=Z",
        "[4,5)us  SYS   decode_syndrome    round=0",
        "[5,6)us  SYS   pauli_frame_update corr=0",
    ])
    program = load_device_program(text, backend())
    kinds = [op.kind for op in program.ops]
    # gate lines lower to ops of the NAMED gate kind (checked vs gate table)
    assert kinds == ["request_ancilla", "CNOT", "H", "measure",
                     "decode_syndrome", "pauli_frame_update"]
    # global site q[100] lowered to the explicit zone qubit anc[0]
    assert [u.resource for u in program.ops[0].uses] == ["anc[0]"]
    assert [u.resource for u in program.ops[1].uses] == ["data[0]", "anc[0]"]
    # decode produces its round token via the decoder service; PFU consumes it
    dec, pfu = program.ops[4], program.ops[5]
    assert dec.service[0].result_token == "decode0"
    assert pfu.consumes[0].kind == "decode0"


def test_unsupported_or_misused_gates_rejected():
    # gate name not in the backend table -> "not supported by this system"
    with pytest.raises(DeviceProgramError, match="not supported"):
        load_device_program(
            HEADER + "[0,1)us  PHYS  gate2q  q[0],q[1] gate=SWAP", backend())
    # arity misuse: H is a 1-qubit gate
    with pytest.raises(DeviceProgramError, match="acts on 1 qubit"):
        load_device_program(
            HEADER + "[0,1)us  PHYS  gate2q  q[0],q[1] gate=H", backend())
    # numeric gate ids are NOT explicit -> rejected
    with pytest.raises(DeviceProgramError, match="explicit names"):
        load_device_program(
            HEADER + "[0,1)us  PHYS  gate2q  q[0],q[1] gate=0", backend())
    # bases are named too
    with pytest.raises(DeviceProgramError, match="explicit names"):
        load_device_program(
            HEADER + "[0,1)us  PHYS  measure  q[100] basis=0", backend())


def test_gate_table_duration_enforced():
    text = HEADER + "[0,5)us  PHYS  gate2q             q[0],q[100] gate=CNOT"
    with pytest.raises(DeviceProgramError, match="hardware facts"):
        load_device_program(text, backend())


def test_request_ancilla_names_exact_qubit():
    program = load_device_program(
        HEADER + "[0,1)us  SYS   request_ancilla    q[101]", backend())
    assert [u.resource for u in program.ops[0].uses] == ["anc[1]"]
    # the old fungible zone form is gone
    with pytest.raises(DeviceProgramError, match=r"expected q\[<site>\]"):
        load_device_program(
            HEADER + "[0,1)us  SYS   request_ancilla    zone=1", backend())


def test_unknown_site_and_bad_lines_rejected():
    with pytest.raises(DeviceProgramError, match="no declared zone"):
        load_device_program(HEADER + "[0,1)us  PHYS  measure  q[999] basis=Z",
                            backend())
    with pytest.raises(DeviceProgramError, match="header"):
        load_device_program("measure q[0]", backend())
    with pytest.raises(DeviceProgramError, match="interval"):
        load_device_program(HEADER + "[3,3)us  PHYS  measure  q[0] basis=Z",
                            backend())


def test_loader_dispatches_dp_files():
    program = load_program(EXAMPLES / "adder_d3.dp", backend())
    assert len(program.ops) == 192
    with pytest.raises(LoadError, match="need the backend"):
        load_program(EXAMPLES / "adder_d3.dp", None)


# --------------------------------------------------------------------------
# Parallel-layer recognition (shared exact-interval rule with Lean)
# --------------------------------------------------------------------------


def test_parallel_layers_recognized():
    b = backend()
    good = load_program(EXAMPLES / "adder_d3.dp", b)
    bad = load_program(EXAMPLES / "adder_d3_bad.dp", b)
    # mirrors Lean's maxSimultaneous on the same files
    assert max_simultaneous(good) == 1
    assert max_simultaneous(bad) == 2
    wide = [g for g in parallel_groups(bad) if len(g[1]) > 1]
    assert len(wide) == 16          # 16 two-op layers (two blocks in lockstep)
    # grouped ops are annotated for inspection
    grouped = [op for op in bad.ops if "parallel_group" in op.metadata]
    assert len(grouped) == 32 and all(op.metadata["group_size"] == 2
                                      for op in grouped)


# --------------------------------------------------------------------------
# The cross-checked adder example (verdicts must match the Lean theorems)
# --------------------------------------------------------------------------


def test_adder_d3_passes_like_lean():
    """VM verdict on the shared file = Lean `schedule_fits` (PASS)."""
    b = backend()
    program = load_program(EXAMPLES / "adder_d3.dp", b)
    result = run_simulation(b, program)
    assert result.ok
    # cross-statistics with the Lean schedule object
    assert result.stats.total_runtime_us == 192      # scheduleWallclockUs
    assert len(program.ops) == 192                   # 12 blocks x 16 SysCalls
    assert sum(1 for op in program.ops if op.kind == "CNOT") == 72
    assert sum(1 for op in program.ops if op.kind == "decode_syndrome") == 36


def test_adder_d3_bad_fails_like_lean():
    """VM verdict on the bad variant = Lean
    `bad_parallel_adder_schedule_rejected` (FAIL).  With explicit-site
    requests both checkers reject for the SAME single reason: two
    simultaneous CNOTs exceed the hardware's CNOT parallelism cap of 1
    (Lean: operation_capacity; VM: CapacityExceeded on gate.CNOT.parallel)."""
    b = backend()
    program = load_program(EXAMPLES / "adder_d3_bad.dp", b)
    result = run_simulation(b, program)
    assert not result.ok
    assert set(result.stats.errors_by_kind) == {"CapacityExceeded"}
    assert any(e.resource == "gate.CNOT.parallel" for e in result.errors)


def test_hardware_reconfiguration_flips_verdict():
    """The hardware catalog is live: the SAME schedule that fails on the
    standard machine (CNOT cap 1) PASSES on the dual-rail machine (CNOT
    cap 2).  Both backend files are GENERATED from
    `FormalRV/System/Params/HardwareCatalog.lean`, and the same flip is
    proven in Lean (`parallel_fails_on_adder_d3` /
    `parallel_ok_on_dualRail`) — the toolchain is not tied to any one
    parameter set."""
    dual = load_backend(EXAMPLES / "adder_d3_dualrail_backend.json")
    program = load_program(EXAMPLES / "adder_d3_bad.dp", dual)
    assert run_simulation(dual, program).ok
    # both backends carry the generated-from-catalog marker
    import json
    for name in ("adder_d3_backend.json", "adder_d3_dualrail_backend.json"):
        doc = json.loads((EXAMPLES / name).read_text(encoding="utf-8"))
        assert "HardwareCatalog.lean" in doc["description"]
