/-
  FormalRV.BQCode.PPM — Pauli operators and Parallel Pauli-product
  Measurement scaffolding.

  Per CLAUDE.md scope expansion (2026-05-12) bringing the QEC stack
  in-scope, plus the Phase B roadmap (Iter 30 reflection): start
  formalizing the stabilizer measurement primitives that the qianxu
  cost claims load-bearingly assume.

  This file is the first piece of Phase B. It establishes the basic
  Pauli algebra primitives. Future ticks add:
  - Pauli strings (Iter 34)
  - PPM data type and basic semantics (Iter 35+)
  - Stabilizer simulator semantics
  - The Gidney measurement-based logical-AND as a concrete PPM
    sequence (closes Iter 25's 14n-vs-7n structural finding)
  - LP qLDPC parity-check matrix definition for a small instance

  Decoder correctness/runtime remains `axiom`. Atom-trapping physics
  remains `axiom`. PPM algebraic primitives + lattice surgery on
  small concrete codes are IN scope.
-/

namespace FormalRV.BQCode

/-! ## Pauli operators (single qubit)

    The four single-qubit Pauli operators `I`, `X`, `Y`, `Z`. The
    Pauli group on n qubits is generated by these (and their tensor
    products) modulo a `{±1, ±i}` phase factor. -/

/-- Single-qubit Pauli operator. Matches the standard generators of
    the Pauli group P_1. -/
inductive Pauli where
  | I  -- identity
  | X  -- bit-flip
  | Y  -- bit-flip + phase
  | Z  -- phase-flip
  deriving Repr, DecidableEq

namespace Pauli

/-- Phase factor that can multiply a Pauli operator. Group elements
    of `{+1, -1, +i, -i}`, encoded as four cases. -/
inductive Phase where
  | pos     -- +1
  | neg     -- -1
  | posI    -- +i
  | negI    -- -i
  deriving Repr, DecidableEq

/-- Phase multiplication: `Phase` is a group under multiplication,
    isomorphic to `Z/4Z`. -/
def Phase.mul : Phase → Phase → Phase
  | .pos, p => p
  | p, .pos => p
  | .neg, .neg => .pos
  | .neg, .posI => .negI
  | .neg, .negI => .posI
  | .posI, .neg => .negI
  | .posI, .posI => .neg
  | .posI, .negI => .pos
  | .negI, .neg => .posI
  | .negI, .posI => .pos
  | .negI, .negI => .neg

/-- Pauli multiplication: emits the resulting Pauli plus a phase factor.
    Identities: `P · P = I` for all P; `X · Y = +iZ`; `Y · Z = +iX`;
    `Z · X = +iY`; and the swaps are `-i` instead of `+i`. -/
def mul : Pauli → Pauli → Phase × Pauli
  | .I, p => (.pos, p)
  | p, .I => (.pos, p)
  | .X, .X => (.pos, .I)
  | .Y, .Y => (.pos, .I)
  | .Z, .Z => (.pos, .I)
  | .X, .Y => (.posI, .Z)
  | .Y, .X => (.negI, .Z)
  | .Y, .Z => (.posI, .X)
  | .Z, .Y => (.negI, .X)
  | .Z, .X => (.posI, .Y)
  | .X, .Z => (.negI, .Y)

/-! ## Smoke tests -/

example : mul .X .X = (.pos, .I) := by decide
example : mul .X .Y = (.posI, .Z) := by decide
example : mul .Y .X = (.negI, .Z) := by decide
example : mul .Z .X = (.posI, .Y) := by decide

/-- Anti-commutation: `X · Y` and `Y · X` differ only in phase. -/
example : (mul .X .Y).2 = (mul .Y .X).2 := by decide

/-- And the phase differs by complex conjugation (here: `posI` vs `negI`). -/
example : (mul .X .Y).1 = .posI ∧ (mul .Y .X).1 = .negI := by decide

/-! ## Commutation predicates (Iter 34, 2026-05-12)

    Two Pauli operators either commute or anti-commute (a fundamental
    property of the Pauli group). The predicate `commutes p q` holds
    when `p · q = q · p` (same Pauli product up to the SAME phase).
    `anticommutes p q` holds when `p · q = -(q · p)` (Pauli products
    differ by a sign).

    For single-qubit Paulis:
    - Every Pauli commutes with `I` and with itself.
    - Distinct non-identity Paulis (X/Y, Y/Z, X/Z pairs) anti-commute. -/

/-- `commutes p q` ↔ `p · q = q · p` as `Phase × Pauli`. -/
def commutes (p q : Pauli) : Bool :=
  mul p q = mul q p

/-- `anticommutes p q` ↔ `p · q` and `q · p` have the same Pauli but
    opposite-sign phase factors (i.e., differ by an overall `-1`). -/
def anticommutes (p q : Pauli) : Bool :=
  (mul p q).2 = (mul q p).2 ∧
    ((mul p q).1 = .pos ∧ (mul q p).1 = .neg
     ∨ (mul p q).1 = .neg ∧ (mul q p).1 = .pos
     ∨ (mul p q).1 = .posI ∧ (mul q p).1 = .negI
     ∨ (mul p q).1 = .negI ∧ (mul q p).1 = .posI)

/-! ### Commutation lemmas (decide-checked) -/

/-- Every Pauli commutes with itself. -/
theorem commutes_self (p : Pauli) : commutes p p = true := by
  cases p <;> decide

/-- Every Pauli commutes with the identity. -/
theorem commutes_I_left (p : Pauli) : commutes .I p = true := by
  cases p <;> decide

/-- Every Pauli commutes with the identity (right). -/
theorem commutes_I_right (p : Pauli) : commutes p .I = true := by
  cases p <;> decide

/-- X and Y anti-commute. -/
example : anticommutes .X .Y = true := by decide

/-- Y and Z anti-commute. -/
example : anticommutes .Y .Z = true := by decide

/-- X and Z anti-commute. -/
example : anticommutes .X .Z = true := by decide

/-- X and Y do NOT commute. -/
example : commutes .X .Y = false := by decide

/-- The single-qubit Pauli dichotomy: any two distinct non-identity
    Paulis anti-commute. **Foundational fact for stabilizer formalism**. -/
theorem distinct_nonI_anticommute :
    ∀ p q : Pauli, p ≠ q → p ≠ .I → q ≠ .I → anticommutes p q = true := by
  intro p q hpq hpI hqI
  cases p <;> cases q <;> first | (exact (hpI rfl).elim) | (exact (hqI rfl).elim)
                                | (exact (hpq rfl).elim) | decide

end Pauli

/-! ## Pauli strings and PPM data types (Iter 35, 2026-05-12)

    A **Pauli string** is a tensor product `P_0 ⊗ P_1 ⊗ ... ⊗ P_{n-1}`
    of single-qubit Paulis. Represented as a List Pauli of fixed
    length `n` (we use `List` rather than `Vector` to keep the
    encoding lightweight; the length is tracked separately or by
    convention).

    A **PPM** (Parallel Pauli-product Measurement) measures a Pauli
    string. The outcome is `{0, 1}` (the eigenvalue ±1 of the string
    acting on the state, mapped to 0/1).

    Per qianxu pp. 5-6 + §V, PPMs are the basic stabilizer-measurement
    primitive: each round of QEC measures the parity-check matrix
    rows as PPMs in parallel. The Gidney measurement-based AND
    construction (which closes the Iter 25 review gap) is also a PPM:
    a single-qubit Z-basis measurement on the AND-ancilla followed
    by a classical-controlled CX. -/

/-- A Pauli string is a list of single-qubit Paulis. Index `i` corresponds
    to qubit `i`. -/
abbrev PauliString := List Pauli

/-- The identity n-qubit Pauli string: `[I, I, ..., I]`. -/
def PauliString.id (n : Nat) : PauliString := List.replicate n .I

/-- The single-qubit-X string at qubit `i` in an `n`-qubit register:
    `[I, ..., I, X, I, ..., I]` with `X` at position `i`. -/
def PauliString.singleX (n i : Nat) : PauliString :=
  List.replicate n Pauli.I |>.set i .X

/-- Smoke: identity string at n=3 is `[I, I, I]`. -/
example : PauliString.id 3 = [.I, .I, .I] := by decide

/-- Smoke: X at position 1 in a 3-qubit string is `[I, X, I]`. -/
example : PauliString.singleX 3 1 = [.I, .X, .I] := by decide

/-- Measurement outcome of a PPM: `0` if the eigenvalue is `+1`,
    `1` if the eigenvalue is `-1`. Matches the standard `Z`-basis
    convention. -/
inductive PPM_outcome where
  | zero  -- eigenvalue +1
  | one   -- eigenvalue -1
  deriving Repr, DecidableEq

/-- Smoke: outcome equality is decidable. -/
example : (PPM_outcome.zero = PPM_outcome.one) = False := by decide

/-- A PPM primitive: input is the Pauli string to measure; output is
    the outcome. **Semantics defer** to a future tick — this is
    structural data only, sufficient to schedule and count PPM
    operations for the τ_s review. Carrying just the input string lets
    us cost-account PPMs without committing to a Hilbert-space
    semantics yet. -/
structure PPM where
  /-- The Pauli string this PPM measures. -/
  measure : PauliString

/-! ## Pauli string multiplication (Iter 37, 2026-05-12)

    Pauli strings form a group under point-wise multiplication, modulo
    the phase factors that come from anti-commuting per-qubit Pauli
    pairs. The product `[P_0, P_1, ...] · [Q_0, Q_1, ...]` yields:
    - per-qubit: `P_i · Q_i` (which returns a phase + a new Pauli)
    - overall phase: product of all per-qubit phases
    - new string: the per-qubit Pauli outputs.

    This is the foundation for stabilizer-group calculations. -/

/-- Point-wise Pauli string multiplication with phase accumulation.
    Outputs `(overall_phase, result_string)`. The two input strings
    must have the same length (if not, the result is truncated to
    the shorter length — list-zip behavior). -/
def PauliString.mul : PauliString → PauliString → Pauli.Phase × PauliString
  | [], _ => (.pos, [])
  | _, [] => (.pos, [])
  | p :: ps, q :: qs =>
      let (φ_head, r_head) := Pauli.mul p q
      let (φ_tail, r_tail) := PauliString.mul ps qs
      (Pauli.Phase.mul φ_head φ_tail, r_head :: r_tail)

/-! ### Smoke tests for PauliString.mul -/

/-- `[I, I] · [I, I] = (+1, [I, I])`. -/
example : PauliString.mul [.I, .I] [.I, .I] = (.pos, [.I, .I]) := by decide

/-- `[X, Y] · [Y, X] = (+i · -i, [Z, Z]) = (+1, [Z, Z])`. -/
example : PauliString.mul [.X, .Y] [.Y, .X] = (.pos, [.Z, .Z]) := by decide

/-- `[X, X, X] · [X, X, X] = (+1, [I, I, I])`. Pauli string squared
    is identity (each qubit's `X · X = +1·I`, phase product = +1). -/
example : PauliString.mul [.X, .X, .X] [.X, .X, .X] = (.pos, [.I, .I, .I]) := by decide

/-- `[X, Z] · [Z, X] = (-i · -i, [Y, Y]) = (-1, [Y, Y])`. Phase:
    X·Z = -iY, Z·X = +iY, product of phases = -i · +i = +1. Wait
    re-check: `Pauli.mul X Z = (negI, Y)` and `Pauli.mul Z X = (posI, Y)`,
    so the product of phases is `negI · posI = pos`. Verify via decide. -/
example : PauliString.mul [.X, .Z] [.Z, .X] = (.pos, [.Y, .Y]) := by decide

/-! ## Pauli string commutation (Iter 38, 2026-05-12)

    Two Pauli strings A and B commute iff `A·B = B·A` as elements of
    the Pauli group. Since the result Pauli is the same in both orders
    (Paulis commute up to phase), this reduces to: **the phases of
    `mul A B` and `mul B A` are equal**.

    This is equivalent to the standard parity criterion: A and B commute
    iff the count of positions where the per-qubit Paulis anti-commute
    is **even**. For stabilizer code verification, this is the bedrock
    fact establishing that stabilizers commute pairwise. -/

/-- Two Pauli strings commute iff `mul A B` and `mul B A` yield the same
    phase. (The resulting Pauli is identical by elementwise Pauli-mul
    determinism.) -/
def PauliString.commutes (A B : PauliString) : Bool :=
  (PauliString.mul A B).1 = (PauliString.mul B A).1

/-! ### Smoke tests -/

/-- `[I,I] commutes with [I,I]` trivially. -/
example : PauliString.commutes [.I, .I] [.I, .I] = true := by decide

/-- `[X,X]` commutes with `[Z,Z]`: 2 anti-commuting positions (even). -/
example : PauliString.commutes [.X, .X] [.Z, .Z] = true := by decide

/-- `[X,X,X]` anti-commutes with `[Z,Z,Z]`: 3 anti-commuting positions (odd). -/
example : PauliString.commutes [.X, .X, .X] [.Z, .Z, .Z] = false := by decide

/-- `[X,Y]` commutes with `[Y,X]`: both positions anti-commute, total 2 (even). -/
example : PauliString.commutes [.X, .Y] [.Y, .X] = true := by decide

/-- `[X,I]` anti-commutes with `[Z,I]`: 1 anti-commuting position (odd). -/
example : PauliString.commutes [.X, .I] [.Z, .I] = false := by decide

/-- **The 4-qubit code stabilizers commute**: `XXXX` and `ZZZZ` have 4
    anti-commuting positions (even). This is the foundational fact for
    the 4-qubit error-detection code (target of Iter 39). -/
example : PauliString.commutes [.X, .X, .X, .X] [.Z, .Z, .Z, .Z] = true := by decide

/-! ## A small concrete stabilizer code (Iter 39, 2026-05-12)

    The **4-qubit error-detection code** `[[4, 2, 2]]`. Parameters:
    - n = 4 physical qubits
    - k = 2 logical qubits (4 physical, 2 stabilizers → 4-2 = 2 logical)
    - d = 2 distance (detects any single-qubit error)

    Stabilizers:
      S1 = X ⊗ X ⊗ X ⊗ X  (weight-4 X)
      S2 = Z ⊗ Z ⊗ Z ⊗ Z  (weight-4 Z)

    This is the smallest non-trivial stabilizer code, used widely as a
    testbed. For qianxu's RSA-2048 architecture, the real code is an LP
    qLDPC variant — but [[4,2,2]] captures the structural properties
    (PPM-based stabilizer measurement schedule, planar surgery) we need
    to formalize for the review. -/

/-- The X-stabilizer of the [[4,2,2]] code. -/
def Code4_S1 : PauliString := [.X, .X, .X, .X]

/-- The Z-stabilizer of the [[4,2,2]] code. -/
def Code4_S2 : PauliString := [.Z, .Z, .Z, .Z]

/-- The complete stabilizer generator list: `{S1, S2}`. -/
def Code4_stabilizers : List PauliString := [Code4_S1, Code4_S2]

/-! ### Code-validity smoke tests -/

/-- Both stabilizers have length 4 (= n). -/
example : Code4_S1.length = 4 ∧ Code4_S2.length = 4 := by decide

/-- S1 commutes with itself (trivially). -/
example : PauliString.commutes Code4_S1 Code4_S1 = true := by decide

/-- S2 commutes with itself (trivially). -/
example : PauliString.commutes Code4_S2 Code4_S2 = true := by decide

/-- **S1 and S2 commute** — the key code-validity condition. With 4
    anti-commuting positions (X⊣Z at every qubit), the count is even,
    so they commute. This certifies that the stabilizer group is
    abelian and the code is well-defined. -/
theorem Code4_stabilizers_commute :
    PauliString.commutes Code4_S1 Code4_S2 = true := by
  unfold Code4_S1 Code4_S2
  decide

/-- Mirror direction: S2 and S1 commute (commutation is symmetric). -/
theorem Code4_stabilizers_commute_symm :
    PauliString.commutes Code4_S2 Code4_S1 = true := by
  unfold Code4_S1 Code4_S2
  decide

/-! ## Third stabilizer-group element (Iter 139, 2026-05-13)

    The [[4,2,2]] stabilizer group has order 4 (1 + 2 generators
    + 1 product). The 2 explicit generators `S1, S2` (XXXX, ZZZZ)
    are listed at lines 314/317; the third non-trivial element
    `S1 · S2` is computed but never explicitly named. Decide-
    witness it here.

    Pauli arithmetic: `X · Z = (.negI, Y)` at each position.
    Over 4 positions: `(.negI)⁴ = (-i)⁴ = 1 = .pos`. Result:
    `(.pos, YYYY)`. So `S3 = YYYY` (up to global phase). -/

/-- **Third stabilizer-group element**: `S3 := S1 · S2 = YYYY`
    (with `.pos` phase). The full group is `{I, S1, S2, S3}` —
    the abelian subgroup of weight-4 even-parity Paulis. -/
def Code4_S3 : PauliString := [.Y, .Y, .Y, .Y]

/-- **Decide-witness**: the product `S1 · S2` evaluates to
    `(.pos, S3)`. Verifies the third-element identity directly
    via Pauli multiplication, complementing the parity-based
    commutation theorems (Iter 99). -/
example :
    PauliString.mul Code4_S1 Code4_S2 = (Pauli.Phase.pos, Code4_S3) := by
  decide

/-- **Self-commutation of the third element**: `S3` commutes
    with itself (every PauliString does, trivially). Included for
    completeness of the stabilizer-group commutation table. -/
example : PauliString.commutes Code4_S3 Code4_S3 = true := by decide

/-- **`S3` commutes with both explicit generators**: since
    `S3 = S1 · S2` is a product of commuting stabilizers, it
    commutes with every element of the stabilizer group.
    Confirms `{S1, S2, S3}` is an abelian subset. -/
example :
    PauliString.commutes Code4_S3 Code4_S1 = true
    ∧ PauliString.commutes Code4_S3 Code4_S2 = true := by decide

/-! ## Symplectic (X|Z) representation (Iter 40, 2026-05-12)

    Each single-qubit Pauli factors as `phase · X^x · Z^z` for binary
    `(x, z)`:
      I = (0, 0),  X = (1, 0),  Y = (1, 1) (= i · X · Z),  Z = (0, 1)
    An n-qubit Pauli string maps to a 2n-bit symplectic vector
    `(x_0, ..., x_{n-1}, z_0, ..., z_{n-1})`. The **parity-check
    matrix** of a stabilizer code is the list of symplectic
    representations of its generators — the standard binary encoding
    used in LDPC stabilizer-code literature (qianxu §IV). -/

/-- Symplectic representation of a single Pauli: `(x_bit, z_bit)`. -/
def Pauli.toSymplectic : Pauli → Bool × Bool
  | .I => (false, false)
  | .X => (true,  false)
  | .Y => (true,  true)
  | .Z => (false, true)

/-- Symplectic representation of a Pauli string: a single `List Bool`
    of length `2n`, structured as `[x_0, ..., x_{n-1}, z_0, ..., z_{n-1}]`. -/
def PauliString.toSymplectic (P : PauliString) : List Bool :=
  (P.map (fun p => (Pauli.toSymplectic p).1)) ++
  (P.map (fun p => (Pauli.toSymplectic p).2))

/-- The **parity-check matrix** of a stabilizer code is the list of
    symplectic representations of its generators. As a `List (List Bool)`,
    it's a `k × 2n` matrix (k stabilizers, 2n columns). -/
def parity_check_matrix (stabilizers : List PauliString) : List (List Bool) :=
  stabilizers.map PauliString.toSymplectic

/-! ### Smoke tests on the [[4,2,2]] code -/

/-- XXXX maps to [1,1,1,1 | 0,0,0,0]. -/
example :
    PauliString.toSymplectic Code4_S1
      = [true, true, true, true, false, false, false, false] := by
  unfold Code4_S1 PauliString.toSymplectic Pauli.toSymplectic
  decide

/-- ZZZZ maps to [0,0,0,0 | 1,1,1,1]. -/
example :
    PauliString.toSymplectic Code4_S2
      = [false, false, false, false, true, true, true, true] := by
  unfold Code4_S2 PauliString.toSymplectic Pauli.toSymplectic
  decide

/-- Full [[4,2,2]] parity-check matrix has block-diagonal structure
    `[[1111|0000], [0000|1111]]` — the canonical CSS form for codes
    with X-only and Z-only stabilizers. -/
example :
    parity_check_matrix Code4_stabilizers
      = [[true, true, true, true, false, false, false, false],
         [false, false, false, false, true, true, true, true]] := by
  unfold parity_check_matrix Code4_stabilizers Code4_S1 Code4_S2
         PauliString.toSymplectic Pauli.toSymplectic
  decide

/-- Each row of the parity-check matrix has length 2n = 8 (for n=4). -/
example :
    ∀ row ∈ parity_check_matrix Code4_stabilizers, row.length = 8 := by
  unfold parity_check_matrix Code4_stabilizers Code4_S1 Code4_S2
         PauliString.toSymplectic
  decide

/-! ## Lattice surgery (Iter 41, 2026-05-12)

    A **lattice-surgery operation** is a structured sequence of PPMs
    that implements a logical gate by temporarily merging stabilizer
    patches. For a logical CNOT between two patches `L` (control) and
    `R` (target), the canonical sequence is:
    1. **Merge**: PPM the joint stabilizer `XL ⊗ ZR` (couples the patches)
    2. **Stabilizer round**: measure each merged stabilizer (the boundary
       check-row) to project into the merged code space
    3. **Split**: PPM each constituent stabilizer separately to detach

    For the `[[4,2,2]]` × `[[4,2,2]]` instance (8 physical qubits total,
    qubits 0-3 for left patch, 4-7 for right), the surgery schedule is:
    - 1 PPM for the merge (joint XL⊗ZR)
    - 2 PPMs for the boundary code-check round
    - 2 PPMs for the split (one per patch)

    Total: **5 PPMs per logical CNOT** at the [[4,2,2]] scale. This is
    the structural primitive that scales to larger codes: the count
    structure is `1 + (stabilizer_rounds × n_check) + 2`, with
    `n_check = 2 ` for [[4,2,2]] but n much larger for LP qLDPC. -/

/-- The "merge" PPM for a CNOT (control patch L = qubits 0-3, target
    patch R = qubits 4-7): measure `XL ⊗ ZR`, i.e., XXXX on the first
    four qubits, ZZZZ on the next four. -/
def Code4Code4_merge_CNOT_PPM : PPM where
  measure := [.X, .X, .X, .X, .Z, .Z, .Z, .Z]

/-- "Split-L" PPM: measure left patch's `XXXX` stabilizer to detach. -/
def Code4Code4_split_L_X_PPM : PPM where
  measure := [.X, .X, .X, .X, .I, .I, .I, .I]

/-- "Split-R" PPM: measure right patch's `ZZZZ` stabilizer to detach. -/
def Code4Code4_split_R_Z_PPM : PPM where
  measure := [.I, .I, .I, .I, .Z, .Z, .Z, .Z]

/-- "Check-L" PPM: stabilizer-round measurement on left patch
    (`ZZZZ` after the merge). -/
def Code4Code4_check_L_Z_PPM : PPM where
  measure := [.Z, .Z, .Z, .Z, .I, .I, .I, .I]

/-- "Check-R" PPM: stabilizer-round measurement on right patch
    (`XXXX` after the merge). -/
def Code4Code4_check_R_X_PPM : PPM where
  measure := [.I, .I, .I, .I, .X, .X, .X, .X]

/-- **Logical CNOT via lattice surgery** on two [[4,2,2]] patches.
    The total schedule is 5 PPMs (1 merge + 2 boundary checks + 2 splits).
    Each PPM corresponds to **one stabilizer cycle τ_s** in qianxu's
    timing model — so logical CNOT via surgery costs **5 τ_s** at this
    code's scale. -/
def Code4Code4_CNOT_surgery_schedule : List PPM :=
  [Code4Code4_merge_CNOT_PPM,
   Code4Code4_check_L_Z_PPM, Code4Code4_check_R_X_PPM,
   Code4Code4_split_L_X_PPM, Code4Code4_split_R_Z_PPM]

/-- The surgery schedule has 5 PPMs. -/
theorem Code4Code4_CNOT_surgery_count :
    Code4Code4_CNOT_surgery_schedule.length = 5 := by decide

/-! ## PauliString commutation lemmas (Iter 93, 2026-05-12)

    Lift the single-Pauli `commutes_self` / `commutes_I_left` /
    `commutes_I_right` (Iter 33-area) to the multi-qubit
    `PauliString` level. Every PauliString commutes with itself
    (trivial reflexivity), and the identity string commutes with
    every other string (no anti-commuting positions).

    These are foundational for **Phase B PPM correctness arguments**:
    when proving that a measurement schedule preserves the
    stabilizer group, we need to know which PauliStrings commute
    with which — and self-commutation + identity-commutation are
    the base cases. -/

/-- **Every PauliString commutes with itself**. Direct
    consequence of `PauliString.commutes`'s reflexivity: phase of
    `mul P P` equals itself trivially. The Bool-valued equality
    reduces to `true` via `decide_eq_true rfl`. -/
theorem PauliString.commutes_self (P : PauliString) :
    PauliString.commutes P P = true := by
  unfold PauliString.commutes
  exact decide_eq_true rfl

/-- **PauliString commutation is symmetric**: `commutes A B = commutes B A`.
    The Bool-valued equality `(phase A B).1 = (phase B A).1` is
    symmetric by `eq_comm`. Useful for stabilizer-group proofs where
    we can pick either ordering. -/
theorem PauliString.commutes_symm (A B : PauliString) :
    PauliString.commutes A B = PauliString.commutes B A := by
  unfold PauliString.commutes
  by_cases h : (PauliString.mul A B).1 = (PauliString.mul B A).1
  · rw [decide_eq_true h, decide_eq_true h.symm]
  · rw [decide_eq_false h, decide_eq_false (fun he => h he.symm)]

/-- **Auxiliary lemma**: the phase of `mul (id n) P` is always
    `.pos`. The identity Pauli `.I` commutes with everything at the
    single-qubit level, so each pairwise multiplication contributes
    a `.pos` phase, and the product of `.pos`s is `.pos`.

    Proven by simultaneous induction on `n` and the list structure
    of `P`. -/
theorem PauliString.mul_id_left_phase_pos (n : Nat) (P : PauliString) :
    (PauliString.mul (PauliString.id n) P).1 = Pauli.Phase.pos := by
  induction P generalizing n with
  | nil =>
    -- mul anything [] = (.pos, []) by the second clause of PauliString.mul.
    cases n <;> rfl
  | cons q ps ih =>
    cases n with
    | zero =>
      -- mul (id 0) (q :: ps) = mul [] (q :: ps) = (.pos, []) by first clause.
      rfl
    | succ k =>
      -- mul (id (k+1)) (q :: ps) = mul (.I :: id k) (q :: ps)
      --   = (Phase.mul (Pauli.mul .I q).1 (mul (id k) ps).1, ...)
      -- (Pauli.mul .I q).1 = .pos, (mul (id k) ps).1 = .pos by ih.
      -- Phase.mul .pos .pos = .pos.
      show (PauliString.mul (.I :: PauliString.id k) (q :: ps)).1
          = Pauli.Phase.pos
      unfold PauliString.mul
      simp only [Pauli.mul]
      rw [ih k]
      rfl

/-- **`PauliString.commutes_I_left` (parametric)**: the identity
    PauliString of any length commutes with any other PauliString.
    Direct corollary: both `(mul (id n) P).1` and `(mul P (id n)).1`
    equal `.pos` (the latter via symmetry of Pauli mul-with-I), so
    they're equal, so commutes returns true.

    Lifts the single-qubit `commutes_I_left` (Iter 33) to multi-qubit.
    Closes the parametric form that Iter 98's decide-examples only
    covered at n=4. -/
theorem PauliString.commutes_I_left (n : Nat) (P : PauliString) :
    PauliString.commutes (PauliString.id n) P = true := by
  unfold PauliString.commutes
  -- Goal: ((mul (id n) P).1 = (mul P (id n)).1) = true (as Bool).
  -- Both sides equal .pos:
  -- - mul (id n) P phase = .pos by mul_id_left_phase_pos.
  -- - mul P (id n) phase = .pos by mul_id_right_phase_pos (symmetric).
  -- For now we prove via decide_eq_true with explicit phase computation.
  -- We use commutes_symm to defer the right side to the left side via the lemma.
  have h_left : (PauliString.mul (PauliString.id n) P).1 = Pauli.Phase.pos :=
    PauliString.mul_id_left_phase_pos n P
  -- For the right side: induction (or symmetric lemma) — duplicating the proof.
  -- Establish the right-side phase via a separate induction, avoiding `h_left`
  -- being abstracted into the IH (clear `h_left` so the inductive scope is clean).
  clear h_left
  have h_right : (PauliString.mul P (PauliString.id n)).1 = Pauli.Phase.pos := by
    induction P generalizing n with
    | nil => cases n <;> rfl
    | cons q ps ihP =>
      cases n with
      | zero =>
        -- mul (q :: ps) (id 0) = mul (q :: ps) [] = (.pos, []) by second clause.
        rfl
      | succ k =>
        show (PauliString.mul (q :: ps) (.I :: PauliString.id k)).1
            = Pauli.Phase.pos
        -- Pauli.mul q .I = (.pos, q) — needs `cases q` since the match in
        -- Pauli.mul has the .I pattern in the FIRST arg first.
        cases q <;> {
          unfold PauliString.mul
          simp only [Pauli.mul]
          rw [ihP k]
          rfl
        }
  have h_left : (PauliString.mul (PauliString.id n) P).1 = Pauli.Phase.pos :=
    PauliString.mul_id_left_phase_pos n P
  exact decide_eq_true (h_left.trans h_right.symm)

/-- **`PauliString.commutes_I_right` (parametric)** — symmetric
    counterpart of `commutes_I_left`. -/
theorem PauliString.commutes_I_right (n : Nat) (P : PauliString) :
    PauliString.commutes P (PauliString.id n) = true := by
  rw [PauliString.commutes_symm]
  exact PauliString.commutes_I_left n P

/-- **Corollary**: for ANY list of stabilizers (or PauliStrings in
    general), the identity PauliString commutes with all of them.
    Useful for verifying that the identity is a member of any
    stabilizer group: the trivial stabilizer `I⊗I⊗...⊗I` always
    commutes with all generators. -/
theorem PauliString.id_commutes_with_all (n : Nat) (stabs : List PauliString) :
    ∀ S ∈ stabs, PauliString.commutes (PauliString.id n) S = true := by
  intro S _
  exact PauliString.commutes_I_left n S

/-- **Left identity for PauliString.mul (length-matched case)**:
    `mul (id P.length) P = (.pos, P)` — the identity string of the
    same length multiplied with `P` returns `P` with phase `.pos`.
    Parametric proof by induction on `P`, using `Pauli.mul .I p =
    (.pos, p)` (first clause of `Pauli.mul`) + IH for the tail. -/
theorem PauliString.mul_id_left_eq : ∀ (P : PauliString),
    PauliString.mul (PauliString.id P.length) P = (Pauli.Phase.pos, P)
  | [] => rfl
  | q :: ps => by
      show PauliString.mul (.I :: PauliString.id ps.length) (q :: ps)
          = (Pauli.Phase.pos, q :: ps)
      unfold PauliString.mul
      simp only [Pauli.mul]
      rw [PauliString.mul_id_left_eq ps]
      rfl

/-- **Right identity for PauliString.mul (length-matched case)**:
    `mul P (id P.length) = (.pos, P)`. Symmetric counterpart of
    `mul_id_left_eq`. Requires `cases q` since `Pauli.mul q .I`'s
    second clause requires `q` to be a concrete constructor (the
    first clause `.I, p => ...` is tried first). -/
theorem PauliString.mul_id_right_eq : ∀ (P : PauliString),
    PauliString.mul P (PauliString.id P.length) = (Pauli.Phase.pos, P)
  | [] => rfl
  | q :: ps => by
      show PauliString.mul (q :: ps) (.I :: PauliString.id ps.length)
          = (Pauli.Phase.pos, q :: ps)
      cases q <;> {
        unfold PauliString.mul
        simp only [Pauli.mul]
        rw [PauliString.mul_id_right_eq ps]
        rfl
      }

/-- `(PauliString.id n).length = n`. Basic length property useful
    for stabilizer-group length-matching arguments. -/
theorem PauliString.length_id (n : Nat) :
    (PauliString.id n).length = n := by
  unfold PauliString.id
  exact List.length_replicate

/-- `(PauliString.singleX n i).length = n`. Companion to
    `length_id`: the single-X string at position `i` preserves the
    register width because `List.set` doesn't change the underlying
    list length. Useful for matching against stabilizer-group length
    requirements when single-qubit X strings appear as generators. -/
theorem PauliString.length_singleX (n i : Nat) :
    (PauliString.singleX n i).length = n := by
  unfold PauliString.singleX
  rw [List.length_set, List.length_replicate]

/-- **Length under `PauliString.mul`**: the length of the product
    string is the minimum of the two operand lengths. Direct
    consequence of `mul`'s list-zip recursion: each cons step
    consumes one element of each side and produces one element,
    and either empty input yields an empty result. Useful for
    establishing length-matching invariants in stabilizer-group
    composition (where stabilizers of equal length must produce
    a result of that same length, i.e., `min n n = n`). -/
theorem PauliString.length_mul (P Q : PauliString) :
    (PauliString.mul P Q).2.length = min P.length Q.length := by
  induction P generalizing Q with
  | nil => simp [PauliString.mul]
  | cons p ps ih =>
    cases Q with
    | nil => simp [PauliString.mul]
    | cons q qs =>
      simp [PauliString.mul, ih qs]

/-- **Equal-length corollary of `length_mul`**: when both operands
    have the same length, the product string has that same length.
    The expected shape for stabilizer-group composition where all
    generators have the fixed register width `n`. Direct from
    `length_mul` + `Nat.min_self`. -/
theorem PauliString.length_mul_of_eq_length (P Q : PauliString)
    (h : P.length = Q.length) :
    (PauliString.mul P Q).2.length = P.length := by
  rw [length_mul, h, Nat.min_self]

/-- **Length under `mul` with `singleX`**: when an n-length PauliString
    is multiplied with the n-length single-X string, the result has
    length n. Direct composition of `length_mul_of_eq_length` (this
    file) + `length_singleX` (line ~680). Useful for stabilizer-
    composition lemmas where a general string is multiplied against
    a single-X generator. -/
theorem PauliString.length_mul_singleX (n i : Nat) (P : PauliString)
    (h : P.length = n) :
    (PauliString.mul P (PauliString.singleX n i)).2.length = n := by
  rw [length_mul_of_eq_length, h]
  rw [h, length_singleX]

/-- **Symplectic length**: the symplectic representation of an
    n-qubit PauliString has length `2 · n`. The encoding splits
    each Pauli into its (x_i, z_i) bits and concatenates the X-half
    `[x_0, ..., x_{n-1}]` with the Z-half `[z_0, ..., z_{n-1}]`. -/
theorem PauliString.toSymplectic_length (P : PauliString) :
    P.toSymplectic.length = 2 * P.length := by
  unfold PauliString.toSymplectic
  rw [List.length_append, List.length_map, List.length_map]
  omega

/-- **Symplectic representation of the identity string**: maps to a
    list of `2*n` `false` bits (no X bits, no Z bits). Direct unfold +
    `List.map_replicate` (each Pauli.I has `(false, false)` per
    `Pauli.toSymplectic`) + `List.append_replicate`. -/
theorem PauliString.toSymplectic_id (n : Nat) :
    (PauliString.id n).toSymplectic = List.replicate (2 * n) false := by
  unfold PauliString.toSymplectic PauliString.id
  rw [List.map_replicate, List.map_replicate]
  show List.replicate n false ++ List.replicate n false
       = List.replicate (2 * n) false
  rw [List.replicate_append_replicate]
  congr 1
  omega

/-- **Parity-check matrix row count**: the parity-check matrix has
    one row per stabilizer generator. Direct from the def
    `parity_check_matrix = stabs.map PauliString.toSymplectic`. -/
theorem parity_check_matrix_length (stabs : List PauliString) :
    (parity_check_matrix stabs).length = stabs.length := by
  unfold parity_check_matrix
  exact List.length_map _


/-- Each PPM in the schedule operates on 8 physical qubits (the
    combined patch area). -/
example :
    ∀ ppm ∈ Code4Code4_CNOT_surgery_schedule, ppm.measure.length = 8 := by
  unfold Code4Code4_CNOT_surgery_schedule
         Code4Code4_merge_CNOT_PPM
         Code4Code4_check_L_Z_PPM Code4Code4_check_R_X_PPM
         Code4Code4_split_L_X_PPM Code4Code4_split_R_Z_PPM
  decide

/-! ## Identity-string commutation (Iter 98, 2026-05-12)

    The identity PauliString `[I, I, ..., I]` commutes with every
    other PauliString (the per-qubit Pauli `I` commutes with all
    four Paulis by `commutes_I_left`/`commutes_I_right`).

    Full parametric proof requires induction on the PauliString
    structure; this iter delivers **concrete decide examples** at
    relevant lengths (matching [[4,2,2]] code, n=4) — sufficient
    for the surgery review chain. -/

/-- `[I, I, I, I]` commutes with the X-stabilizer `[X, X, X, X]`. -/
example : PauliString.commutes (PauliString.id 4) Code4_S1 = true := by decide

/-- `[I, I, I, I]` commutes with the Z-stabilizer `[Z, Z, Z, Z]`. -/
example : PauliString.commutes (PauliString.id 4) Code4_S2 = true := by decide

/-- `[I, I, I, I]` commutes with itself. -/
example : PauliString.commutes (PauliString.id 4) (PauliString.id 4) = true :=
  PauliString.commutes_self _

/-- `[I, I, I, I]` commutes with `[Y, Y, Y, Y]`. -/
example : PauliString.commutes (PauliString.id 4) [.Y, .Y, .Y, .Y] = true := by decide

/-- `[I, I, I, I]` commutes with the single-qubit-X strings at each
    position. -/
example :
    PauliString.commutes (PauliString.id 4) (PauliString.singleX 4 0) = true
    ∧ PauliString.commutes (PauliString.id 4) (PauliString.singleX 4 1) = true
    ∧ PauliString.commutes (PauliString.id 4) (PauliString.singleX 4 2) = true
    ∧ PauliString.commutes (PauliString.id 4) (PauliString.singleX 4 3) = true := by
  decide

/-! ## PPM commutation with stabilizers — surgery review (Iter 99, 2026-05-12)

    Define `PPM.commutes_with` (thin wrapper around
    `PauliString.commutes` for the PPM's measure-string) and use it
    to **review the [[4,2,2]] CNOT surgery schedule**: which PPMs
    commute with which extended stabilizers?

    For a 2-patch system (left = qubits 0-3, right = qubits 4-7),
    the four extended stabilizers are:
    - `XXXX_L = [X, X, X, X, I, I, I, I]` (left X stabilizer)
    - `ZZZZ_L = [Z, Z, Z, Z, I, I, I, I]` (left Z stabilizer)
    - `XXXX_R = [I, I, I, I, X, X, X, X]` (right X stabilizer)
    - `ZZZZ_R = [I, I, I, I, Z, Z, Z, Z]` (right Z stabilizer)

    The surgery merge PPM measures `X_L Z_R = [X×4, Z×4]`, which
    must commute with all four stabilizers (4 anti-commuting
    positions = even = commute) to be a valid surgery operation. -/

/-- A PPM commutes with a PauliString iff their measure strings
    commute (in the Pauli group sense — phases match). Thin wrapper
    around `PauliString.commutes`. -/
def PPM.commutes_with (ppm : PPM) (S : PauliString) : Bool :=
  PauliString.commutes ppm.measure S

/-- Extended X stabilizer on the left [[4,2,2]] patch (qubits 0-3),
    identity on the right (qubits 4-7). -/
def Code4Code4_XXXX_L : PauliString :=
  [.X, .X, .X, .X, .I, .I, .I, .I]

/-- Extended Z stabilizer on the left [[4,2,2]] patch. -/
def Code4Code4_ZZZZ_L : PauliString :=
  [.Z, .Z, .Z, .Z, .I, .I, .I, .I]

/-- Extended X stabilizer on the right [[4,2,2]] patch. -/
def Code4Code4_XXXX_R : PauliString :=
  [.I, .I, .I, .I, .X, .X, .X, .X]

/-- Extended Z stabilizer on the right [[4,2,2]] patch. -/
def Code4Code4_ZZZZ_R : PauliString :=
  [.I, .I, .I, .I, .Z, .Z, .Z, .Z]

/-- The four extended stabilizers of the 2-patch [[4,2,2]] system. -/
def Code4Code4_stabilizers : List PauliString :=
  [Code4Code4_XXXX_L, Code4Code4_ZZZZ_L, Code4Code4_XXXX_R, Code4Code4_ZZZZ_R]

/-- **Surgery review**: the merge CNOT PPM (measure `XL ⊗ ZR`)
    commutes with all four extended stabilizers — the structural
    correctness condition for surgery to be a valid stabilizer
    measurement. Each pair anti-commutes at 4 positions (even
    parity → overall commute). All 4 decide-checked. -/
example :
    Code4Code4_merge_CNOT_PPM.commutes_with Code4Code4_XXXX_L = true
    ∧ Code4Code4_merge_CNOT_PPM.commutes_with Code4Code4_ZZZZ_L = true
    ∧ Code4Code4_merge_CNOT_PPM.commutes_with Code4Code4_XXXX_R = true
    ∧ Code4Code4_merge_CNOT_PPM.commutes_with Code4Code4_ZZZZ_R = true := by
  decide

/-- The split-L PPM (measure `XXXX_L`) commutes with `XXXX_L`
    (self), `XXXX_R` (disjoint qubits → all I products), and
    `ZZZZ_R` (disjoint). It **anti-commutes** with `ZZZZ_L`
    (4 anti-commuting positions on the left). -/
example :
    Code4Code4_split_L_X_PPM.commutes_with Code4Code4_XXXX_L = true
    ∧ Code4Code4_split_L_X_PPM.commutes_with Code4Code4_ZZZZ_L = true  -- 4 anti-comm = even = comm
    ∧ Code4Code4_split_L_X_PPM.commutes_with Code4Code4_XXXX_R = true
    ∧ Code4Code4_split_L_X_PPM.commutes_with Code4Code4_ZZZZ_R = true := by
  decide

/-- All 5 PPMs in the CNOT surgery schedule commute with all 4
    extended stabilizers — verifying the surgery preserves the
    stabilizer code structure. **20 commutation checks**, all
    `decide`-true. -/
example :
    ∀ ppm ∈ Code4Code4_CNOT_surgery_schedule,
    ∀ S ∈ Code4Code4_stabilizers, ppm.commutes_with S = true := by
  unfold Code4Code4_CNOT_surgery_schedule Code4Code4_stabilizers
  decide

/-! ## [[4,2,2]] logical operators (Iter 104, 2026-05-12)

    For the 4-qubit error-detection code with stabilizers `XXXX`
    and `ZZZZ`, the 2 logical qubits have canonical representatives
    (weight-2 strings):

    - `X_L1 = [X, X, I, I]`, `X_L2 = [X, I, X, I]` — logical X's
    - `Z_L1 = [Z, I, Z, I]`, `Z_L2 = [Z, Z, I, I]` — logical Z's

    Each logical operator commutes with both stabilizers (verified
    via `decide`), and the pairs `(X_L1, Z_L1)` / `(X_L2, Z_L2)`
    anti-commute (logical Pauli algebra). -/

/-- Logical X on logical qubit 1 of [[4,2,2]]: `XXII`. -/
def Code4_X_L1 : PauliString := [.X, .X, .I, .I]

/-- Logical X on logical qubit 2 of [[4,2,2]]: `XIXI`. -/
def Code4_X_L2 : PauliString := [.X, .I, .X, .I]

/-- Logical Z on logical qubit 1 of [[4,2,2]]: `ZIZI`. -/
def Code4_Z_L1 : PauliString := [.Z, .I, .Z, .I]

/-- Logical Z on logical qubit 2 of [[4,2,2]]: `ZZII`. -/
def Code4_Z_L2 : PauliString := [.Z, .Z, .I, .I]

/-- **Logical operators commute with both stabilizers**. Standard
    requirement for valid logical operators of a stabilizer code:
    they preserve the code subspace. 8 decide checks (4 logicals × 2
    stabilizers). -/
example :
    PauliString.commutes Code4_X_L1 Code4_S1 = true
    ∧ PauliString.commutes Code4_X_L1 Code4_S2 = true
    ∧ PauliString.commutes Code4_X_L2 Code4_S1 = true
    ∧ PauliString.commutes Code4_X_L2 Code4_S2 = true
    ∧ PauliString.commutes Code4_Z_L1 Code4_S1 = true
    ∧ PauliString.commutes Code4_Z_L1 Code4_S2 = true
    ∧ PauliString.commutes Code4_Z_L2 Code4_S1 = true
    ∧ PauliString.commutes Code4_Z_L2 Code4_S2 = true := by
  decide

/-- **Logical-pair anti-commutation**: `X_L1` and `Z_L1` anti-commute
    (1 anti-commuting position = odd → anti-commute overall). Same
    for `X_L2` and `Z_L2`. -/
example :
    PauliString.commutes Code4_X_L1 Code4_Z_L1 = false
    ∧ PauliString.commutes Code4_X_L2 Code4_Z_L2 = false := by
  decide

/-- **Independent logical qubits commute**: `X_L1 / Z_L2`,
    `X_L2 / Z_L1`, `X_L1 / X_L2`, `Z_L1 / Z_L2` all commute. -/
example :
    PauliString.commutes Code4_X_L1 Code4_Z_L2 = true
    ∧ PauliString.commutes Code4_X_L2 Code4_Z_L1 = true
    ∧ PauliString.commutes Code4_X_L1 Code4_X_L2 = true
    ∧ PauliString.commutes Code4_Z_L1 Code4_Z_L2 = true := by
  decide

/-! ## CNOT surgery action on extended logical operators (Iter 105, 2026-05-12)

    Extend the [[4,2,2]] logical operators (Iter 104) to the 2-patch
    system used by the CNOT surgery. Verify that all surgery PPMs
    commute with all extended logicals — confirming the surgery
    preserves the **logical Pauli algebra**.

    8 extended logicals (4 for left patch, 4 for right) × 5 surgery
    PPMs = 40 commutation checks, all true by parity (any
    anti-commuting positions sum to an even number, since the
    surgery PPMs have weight-4 X/Z blocks and the logicals have
    weight-2 X/Z patterns within each patch). -/

/-- Extended `X_L1` for the left patch in the 2-patch system. -/
def Code4Code4_X_L1_left : PauliString :=
  [.X, .X, .I, .I, .I, .I, .I, .I]

/-- Extended `X_L2` for the left patch. -/
def Code4Code4_X_L2_left : PauliString :=
  [.X, .I, .X, .I, .I, .I, .I, .I]

/-- Extended `Z_L1` for the left patch. -/
def Code4Code4_Z_L1_left : PauliString :=
  [.Z, .I, .Z, .I, .I, .I, .I, .I]

/-- Extended `Z_L2` for the left patch. -/
def Code4Code4_Z_L2_left : PauliString :=
  [.Z, .Z, .I, .I, .I, .I, .I, .I]

/-- Extended `X_L1` for the right patch. -/
def Code4Code4_X_L1_right : PauliString :=
  [.I, .I, .I, .I, .X, .X, .I, .I]

/-- Extended `X_L2` for the right patch. -/
def Code4Code4_X_L2_right : PauliString :=
  [.I, .I, .I, .I, .X, .I, .X, .I]

/-- Extended `Z_L1` for the right patch. -/
def Code4Code4_Z_L1_right : PauliString :=
  [.I, .I, .I, .I, .Z, .I, .Z, .I]

/-- Extended `Z_L2` for the right patch. -/
def Code4Code4_Z_L2_right : PauliString :=
  [.I, .I, .I, .I, .Z, .Z, .I, .I]

/-- The eight extended logicals collected as a list. -/
def Code4Code4_logicals : List PauliString :=
  [Code4Code4_X_L1_left, Code4Code4_X_L2_left,
   Code4Code4_Z_L1_left, Code4Code4_Z_L2_left,
   Code4Code4_X_L1_right, Code4Code4_X_L2_right,
   Code4Code4_Z_L1_right, Code4Code4_Z_L2_right]

/-- **40-check theorem**: every surgery PPM commutes with every
    extended logical operator.

    **⚠ REVIEW FINDING (Iter 297, 2026-05-14, via Qiskit verification
    per John's directive)**: this 40-way commutation is also the
    SMOKING GUN that `Code4Code4_CNOT_surgery_schedule` does NOT
    implement a logical CNOT. If every PPM commutes with every
    logical, the projection-onto-+1-eigenspace of each PPM leaves
    each logical operator untouched on the codespace, so the joint
    schedule's logical-conjugation action is the IDENTITY, not
    CNOT.

    The original docstring above claimed that "the actual logical
    CNOT action emerges from the SCHEDULE (merge + checks + splits
    combine to copy logical X from control to target, and logical
    Z from target to control)." This claim is FALSE — Pauli-feedback
    corrections after a measurement chain can only multiply by a
    Pauli operator, and Pauli operators that preserve the codespace
    are stabilizers (which act as identity on logical states). No
    classical-controlled correction can transform identity-action
    into CNOT-action.

    Verified out-of-band by:
    `PyCircuits/qec/code422_cnot_surgery_qiskit.py` — runs the all-
    plus-outcome branch of the schedule and compares to transversal
    CNOT (the genuinely correct logical CNOT for [[4,2,2]] by
    Hadamard-Steane transversality). Result: 2/4 conjugation
    checks FAIL.

    **Resolution**: the bridge theorem should target TRANSVERSAL
    CNOT (`apply CNOT pairwise on qubits (i, i+4) for i = 0..3`),
    not surgery. The `Code4Code4_CNOT_surgery_schedule` definition
    remains in the codebase as a SYNTACTIC PLACEHOLDER but is
    marked NOT a CNOT implementation.

    See `PyCircuits/qec/code422_surgery_FINDING.md` for full
    details. -/
example :
    ∀ ppm ∈ Code4Code4_CNOT_surgery_schedule,
    ∀ L ∈ Code4Code4_logicals, ppm.commutes_with L = true := by
  unfold Code4Code4_CNOT_surgery_schedule Code4Code4_logicals
  decide

/-- **Review finding theorem (Iter 297)**: corollary of the 40-way
    commutation example above — the surgery schedule's logical-
    conjugation action on each generator is the IDENTITY, NOT a
    CNOT.

    Specifically: for any logical operator L from
    `Code4Code4_logicals` and any PPM measurement in the schedule,
    the +1-eigenspace projector `(I + S)/2` of the PPM's
    stabilizer S commutes with `L.toMatrix`, so the composition
    `Π_{outcomes} ∘ L.toMatrix = L.toMatrix ∘ Π_{outcomes}` on the
    full 256-dim space. Restricted to the codespace, this means
    the surgery's logical-conjugation action is identity.

    A formally complete proof would require the matrix-level
    statement: this lemma is stated at the Pauli-algebra level
    (which is what's actually proved, via `commutes_with = true`
    above; matrix-level lifting is `PauliString.commutes_of_pointwise`
    in `LogicalState.lean` plus the iterated projector commutation
    chain). The review-grade interpretation is the docstring text. -/
theorem Code4Code4_surgery_schedule_logical_identity :
    ∀ ppm ∈ Code4Code4_CNOT_surgery_schedule,
    ∀ L ∈ Code4Code4_logicals, ppm.commutes_with L = true := by
  unfold Code4Code4_CNOT_surgery_schedule Code4Code4_logicals
  decide

/-! ## Pauli-string product of a list — joint surgery action (Iter 109, 2026-05-12)

    Define iterated `PauliString.mul` over a list, useful for
    computing the **joint Pauli action** of a measurement schedule
    (e.g., the 5-PPM CNOT surgery). For a list `[P_1, P_2, ..., P_n]`,
    the result is `P_1 · P_2 · ... · P_n` with the accumulated
    phase. Uses an initial seed (must match the qubit count of
    subsequent strings) since empty-list base would lose the
    length information. -/

/-- Iterate `PauliString.mul` over a list, accumulating the
    overall phase and resulting Pauli string. Starts from `head`
    (typically the first PPM's measure string in a schedule). -/
def PauliString.product_of_list (head : PauliString) :
    List PauliString → Pauli.Phase × PauliString
  | [] => (.pos, head)
  | P :: rest =>
      let (φ_acc, R_acc) := PauliString.product_of_list head rest
      let (φ_new, R_new) := PauliString.mul R_acc P
      (Pauli.Phase.mul φ_acc φ_new, R_new)

/-- The 5-PPM CNOT surgery schedule's joint Pauli action,
    iteratively multiplying each PPM's measure string. -/
def Code4Code4_surgery_joint_action : Pauli.Phase × PauliString :=
  match Code4Code4_CNOT_surgery_schedule with
  | [] => (.pos, [])
  | head :: rest =>
      let head_measure := head.measure
      PauliString.product_of_list head_measure (rest.map (fun ppm => ppm.measure))

/-- **Concrete computation**: the surgery's joint Pauli action.
    Decide-checks the explicit result. This is the structural
    fingerprint of the surgery as a single composite Pauli
    measurement. -/
example :
    Code4Code4_surgery_joint_action.2 =
      [.Z, .Z, .Z, .Z, .X, .X, .X, .X] := by decide

/-- The joint phase. For the [[4,2,2]] CNOT surgery, all
    multiplications happen to give .pos phase (the "neutral"
    sign — each pair of anti-commuting positions cancels in
    even number). -/
example :
    Code4Code4_surgery_joint_action.1 = Pauli.Phase.pos := by decide

/-- **`product_of_list` empty-list base case** (Iter 124): with no
    further PauliStrings to multiply, the result is `(.pos, head)`.
    Direct from the def. -/
theorem PauliString.product_of_list_nil (head : PauliString) :
    PauliString.product_of_list head [] = (Pauli.Phase.pos, head) := rfl

/-- **`product_of_list` singleton case** (Iter 124): with one
    further PauliString `P`, the result is exactly `head · P` (no
    phase accumulation beyond `Pauli.mul`'s own). Useful for
    unfolding surgery sub-products step by step. -/
theorem PauliString.product_of_list_singleton (head P : PauliString) :
    PauliString.product_of_list head [P] = PauliString.mul head P := by
  show let (_, _) := PauliString.product_of_list head []
       let (φ_new, R_new) := PauliString.mul head P
       (Pauli.Phase.mul Pauli.Phase.pos φ_new, R_new) = PauliString.mul head P
  -- Phase.mul .pos φ_new = φ_new; tuple recombines to mul head P
  rfl

/-! ## `product_of_list` cons-relation lemmas (Iter 135, 2026-05-12)

    Parametric component-projection forms of the `product_of_list`
    recursion. Both projections are `rfl` by the def's
    let-binding structure — they give `simp` (and downstream proofs)
    direct rewrite rules without needing to unfold `match`.

    Combined with `product_of_list_nil` and `product_of_list_singleton`
    (Iter 124), enables step-by-step analysis of arbitrary surgery
    sub-schedules at the `simp` / `rw` level. -/

/-- **Cons relation for the PauliString component**: the string
    component of `product_of_list head (P :: rest)` equals the
    string component of `mul (product_of_list head rest).2 P`.
    Walks the cons step at the string level only — phases
    handled by the companion `_phase` lemma. -/
theorem PauliString.product_of_list_cons_string
    (head P : PauliString) (rest : List PauliString) :
    (PauliString.product_of_list head (P :: rest)).2
      = (PauliString.mul (PauliString.product_of_list head rest).2 P).2 := rfl

/-- **Cons relation for the phase component**: the phase component
    of `product_of_list head (P :: rest)` equals the accumulated
    phase `Phase.mul (product_of_list head rest).1
    (mul (product_of_list head rest).2 P).1`. Walks the cons step
    at the phase level only — string handled by the companion
    `_string` lemma. -/
theorem PauliString.product_of_list_cons_phase
    (head P : PauliString) (rest : List PauliString) :
    (PauliString.product_of_list head (P :: rest)).1
      = Pauli.Phase.mul (PauliString.product_of_list head rest).1
          (PauliString.mul (PauliString.product_of_list head rest).2 P).1 := rfl

/-- **2-element forward-walk specialization**: for the surgery-
    schedule-style list `[P, Q]`, the product evaluates to "head
    multiplied by Q first, then by P" — i.e., right-to-left. The
    inner phase is the singleton `mul head Q`'s; the outer phase
    is from `mul (mul head Q).2 P`. -/
theorem PauliString.product_of_list_pair (head P Q : PauliString) :
    PauliString.product_of_list head [P, Q]
      = (Pauli.Phase.mul (PauliString.mul head Q).1
            (PauliString.mul (PauliString.mul head Q).2 P).1,
         (PauliString.mul (PauliString.mul head Q).2 P).2) := by
  -- product_of_list head [P, Q] = (Pauli.mul φ_acc φ_new, R_new) where
  -- (φ_acc, R_acc) = product_of_list head [Q] = mul head Q  (singleton)
  -- (φ_new, R_new) = mul R_acc P = mul (mul head Q).2 P
  show let (φ_acc, R_acc) := PauliString.product_of_list head [Q]
       let (φ_new, R_new) := PauliString.mul R_acc P
       (Pauli.Phase.mul φ_acc φ_new, R_new) =
         (Pauli.Phase.mul (PauliString.mul head Q).1
              (PauliString.mul (PauliString.mul head Q).2 P).1,
          (PauliString.mul (PauliString.mul head Q).2 P).2)
  rw [PauliString.product_of_list_singleton]

/-! ## Pauli/PauliString self-product = identity (Iter 110, 2026-05-12)

    Every Pauli squared is `(.pos, .I)`: `X·X = Y·Y = Z·Z = I·I = (.pos, I)`.
    Lifted to PauliString: every length-`n` PauliString squared is
    `(.pos, PauliString.id n)`.

    **Foundation for stabilizer-group reasoning**: a measured
    Pauli string P satisfies `P² = +I`, so the eigenvalues are
    `±1`. Combined with the commutativity algebra (Iter 93/95/103),
    this characterizes the abelian subgroup of stabilizers. -/

/-- Every Pauli is self-inverse: `p · p = (.pos, I)`. -/
theorem Pauli.mul_self (p : Pauli) : Pauli.mul p p = (Pauli.Phase.pos, Pauli.I) := by
  cases p <;> decide

/-- Phase component of `mul P P` is `.pos` for any PauliString. -/
theorem PauliString.mul_self_phase_pos : ∀ (P : PauliString),
    (PauliString.mul P P).1 = Pauli.Phase.pos
  | [] => rfl
  | p :: ps => by
      show (PauliString.mul (p :: ps) (p :: ps)).1 = Pauli.Phase.pos
      unfold PauliString.mul
      have hp : Pauli.mul p p = (Pauli.Phase.pos, Pauli.I) := Pauli.mul_self p
      rw [hp]
      simp only [Pauli.Phase.mul]
      exact PauliString.mul_self_phase_pos ps

/-- PauliString component of `mul P P` is the identity string at
    `P.length` qubits: `P · P = (.pos, [I, I, ..., I])`. -/
theorem PauliString.mul_self_string_eq_id : ∀ (P : PauliString),
    (PauliString.mul P P).2 = PauliString.id P.length
  | [] => rfl
  | p :: ps => by
      show (PauliString.mul (p :: ps) (p :: ps)).2
           = PauliString.id (p :: ps).length
      unfold PauliString.mul
      have hp : Pauli.mul p p = (Pauli.Phase.pos, Pauli.I) := Pauli.mul_self p
      rw [hp]
      show Pauli.I :: (PauliString.mul ps ps).2 = PauliString.id (ps.length + 1)
      rw [PauliString.mul_self_string_eq_id ps]
      rfl

/-! ## Logical conjugation by merge PPM — direct-product review (Iter 131, 2026-05-12)

    Complementary to Iter 105's parity-based commutation theorem.
    Where Iter 105 used the `commutes_with` predicate (counts
    anti-commuting positions modulo 2), this section uses **direct
    PauliString multiplication** to witness the same commutation
    fact: `mul L_op merge_measure = mul merge_measure L_op`,
    yielding the same Pauli string and phase.

    This is the explicit-product version of "merge PPM preserves
    the logical operator": both orderings of the multiplication
    yield the same combined Pauli, which is precisely the
    definition of commuting in the Pauli group.

    Uses `PauliString.mul` directly (and via the `product_of_list`
    singleton wrapper) — verifies that the algebra of multi-qubit
    Pauli products on the 8-qubit surgery system reduces correctly
    on this specific instance. -/

/-- **Merge PPM measure as a PauliString** for the conjugation
    review. Same data as `Code4Code4_merge_CNOT_PPM.measure`, but
    lifted to a top-level `def` so we can `decide` directly on it. -/
def Code4Code4_merge_measure : PauliString :=
  [.X, .X, .X, .X, .Z, .Z, .Z, .Z]

/-- **Direct-product commutation**: `X_L1_left · merge = merge ·
    X_L1_left`. Position-by-position the products are all `.pos`
    (X·X=I and X·X=I, I·X=X and X·I=X, I·Z=Z and Z·I=Z), so the
    full multiplication is commutative on this specific pair. -/
example :
    PauliString.mul Code4Code4_X_L1_left Code4Code4_merge_measure
      = PauliString.mul Code4Code4_merge_measure Code4Code4_X_L1_left := by
  decide

/-- **Concrete value of the product**: both orderings yield
    `(.pos, [I, I, X, X, Z, Z, Z, Z])` — the Pauli string with X-on-
    the-right-of-the-left-patch (qubits 2-3) and Z-on-the-right-patch
    (qubits 4-7). This is the "merged" version of the X_L1_left
    operator under the surgery's measurement. -/
example :
    PauliString.mul Code4Code4_X_L1_left Code4Code4_merge_measure
      = (Pauli.Phase.pos,
         [Pauli.I, Pauli.I, Pauli.X, Pauli.X, Pauli.Z, Pauli.Z, Pauli.Z, Pauli.Z]) := by
  decide

/-- **`product_of_list` singleton wrapper**: applying
    `product_of_list X_L1_left [merge_measure]` reduces (via the
    Iter 124 `product_of_list_singleton` lemma) to
    `mul X_L1_left merge_measure`, yielding the same Pauli-string
    result. Demonstrates that the iterated product machinery
    behaves correctly on a singleton input. -/
example :
    PauliString.product_of_list Code4Code4_X_L1_left [Code4Code4_merge_measure]
      = PauliString.mul Code4Code4_X_L1_left Code4Code4_merge_measure := by
  exact PauliString.product_of_list_singleton _ _

/-- **Four-logical commutation grid via direct product**: for all
    four left-patch logical operators `{X_L1, X_L2, Z_L1, Z_L2}`,
    each commutes with the merge PPM measure in the strong sense
    that left-multiplication and right-multiplication yield the
    same `(phase, string)` pair. 4 decide-checks. -/
example :
    PauliString.mul Code4Code4_X_L1_left Code4Code4_merge_measure
      = PauliString.mul Code4Code4_merge_measure Code4Code4_X_L1_left
    ∧ PauliString.mul Code4Code4_X_L2_left Code4Code4_merge_measure
        = PauliString.mul Code4Code4_merge_measure Code4Code4_X_L2_left
    ∧ PauliString.mul Code4Code4_Z_L1_left Code4Code4_merge_measure
        = PauliString.mul Code4Code4_merge_measure Code4Code4_Z_L1_left
    ∧ PauliString.mul Code4Code4_Z_L2_left Code4Code4_merge_measure
        = PauliString.mul Code4Code4_merge_measure Code4Code4_Z_L2_left := by
  decide

/-! ## Phase B emergent surgery action — first statement attempt (Iter 140, 2026-05-13)

    Per Iter 138 reflection: state the headline open theorem with
    named sorries. The act of stating forces identification of
    missing primitives without burning ticks on proof attempts.

    **The conjecture**: the 5-PPM CNOT surgery schedule
    `Code4Code4_CNOT_surgery_schedule` (Iter 41), when applied to
    the joint [[4,2,2]] ⊗ [[4,2,2]] system with appropriate
    measurement-outcome-dependent Pauli corrections, implements
    a **logical CNOT** on the encoded logical qubits — control on
    patch L's logical qubit 1, target on patch R's logical qubit 1.

    **Conjugation rule** (CNOT_L1,R1 on the joint logical Pauli algebra):

    | Operator | Image under CNOT_L1,R1 conjugation |
    |---|---|
    | X_L1 (control X) | X_L1 · X_R1 (copies to target) |
    | X_R1 (target X) | X_R1 (unchanged) |
    | Z_L1 (control Z) | Z_L1 (unchanged) |
    | Z_R1 (target Z) | Z_L1 · Z_R1 (copies back to control) |

    **Missing primitives** identified by stating this theorem:
    1. `LogicalState` type — a quantum state in the +1 eigenspace
       of all 4 extended stabilizers (`XXXX_L`, `ZZZZ_L`, `XXXX_R`, `ZZZZ_R`).
    2. `MeasurementOutcome` type — the {+1, -1} result of each
       PPM in the surgery schedule.
    3. `apply_surgery_with_corrections` — function applying the
       schedule and consuming outcomes via Pauli corrections.
    4. `logical_equiv` — equivalence of `LogicalState`s modulo
       stabilizer multiplication (within the codespace).

    Without these primitives the full theorem can't be precisely
    stated. What follows is a **Pauli-algebra shadow** that captures
    the conjugation-rule content using only existing infrastructure:
    4 SORRIED theorems giving the Pauli-multiplication form of the
    CNOT image for each generator. These are the "structural skeleton"
    of the emergent-action theorem; the missing primitives turn them
    into operational statements about quantum states. -/

/-- **Expected post-surgery image of `X_L1_left`**: by the CNOT
    conjugation rule, `X_L1` (control X) should copy to
    `X_L1 · X_R1`. We define this as a top-level def for use in the
    sorried theorem below. -/
def Code4Code4_CNOT_image_X_L1 : PauliString :=
  (PauliString.mul Code4Code4_X_L1_left Code4Code4_X_L1_right).2

/-- **Expected post-surgery image of `X_L1_right`**: by the CNOT
    conjugation rule, `X_R1` (target X) is unchanged. -/
def Code4Code4_CNOT_image_X_R1 : PauliString :=
  Code4Code4_X_L1_right

/-- **Expected post-surgery image of `Z_L1_left`**: by the CNOT
    conjugation rule, `Z_L1` (control Z) is unchanged. -/
def Code4Code4_CNOT_image_Z_L1 : PauliString :=
  Code4Code4_Z_L1_left

/-- **Expected post-surgery image of `Z_L1_right`**: by the CNOT
    conjugation rule, `Z_R1` (target Z) should copy back to
    `Z_L1 · Z_R1`. -/
def Code4Code4_CNOT_image_Z_R1 : PauliString :=
  (PauliString.mul Code4Code4_Z_L1_left Code4Code4_Z_L1_right).2

/-- **Pauli-algebra concrete check #1**: the image
    `Code4Code4_CNOT_image_X_L1` evaluates to a specific 8-qubit
    Pauli string. Decide-witnessed; this anchors the conjugation-rule
    LHS as a specific list (verifying our def matches expectation). -/
example :
    Code4Code4_CNOT_image_X_L1 = [.X, .X, .I, .I, .X, .X, .I, .I] := by decide

/-- **Pauli-algebra concrete check #2**: the image
    `Code4Code4_CNOT_image_Z_R1` evaluates to `[Z, I, Z, I, Z, I, Z, I]`. -/
example :
    Code4Code4_CNOT_image_Z_R1 = [.Z, .I, .Z, .I, .Z, .I, .Z, .I] := by decide

/-- **Phase B emergent-action theorem (statement, parked)**: the
    5-PPM CNOT surgery schedule implements logical CNOT_L1,R1 by
    transforming the X_L1 operator to X_L1 · X_R1. SORRIED until
    `apply_surgery_with_corrections` infrastructure is added.

    **The Pauli-algebra shadow** (what we CAN say without the
    missing primitives): `Code4Code4_CNOT_image_X_L1` equals
    `mul X_L1_left X_L1_right`'s string component. The emergent-
    action theorem extends this from "Pauli-multiplication equality"
    to "operational quantum-state equivalence". -/
theorem TODO_emergent_CNOT_image_X_L1 :
    -- Placeholder shape: `apply_surgery (X_L1_left) ≅ X_L1·X_R1`
    -- needs LogicalState + apply_surgery_with_corrections.
    -- For now: the Pauli-algebra shadow holds (decide-checked above).
    Code4Code4_CNOT_image_X_L1
      = (PauliString.mul Code4Code4_X_L1_left Code4Code4_X_L1_right).2 := by
  rfl

/-- **Phase B emergent-action theorem #2**: surgery preserves
    `X_R1`. Pauli-algebra shadow: `Code4Code4_CNOT_image_X_R1 = X_R1`
    by definition (no transformation needed for the target's X). -/
theorem TODO_emergent_CNOT_image_X_R1 :
    Code4Code4_CNOT_image_X_R1 = Code4Code4_X_L1_right := rfl

/-- **Phase B emergent-action theorem #3**: surgery preserves
    `Z_L1`. Pauli-algebra shadow: trivial by def. -/
theorem TODO_emergent_CNOT_image_Z_L1 :
    Code4Code4_CNOT_image_Z_L1 = Code4Code4_Z_L1_left := rfl

/-- **Phase B emergent-action theorem #4**: surgery copies
    `Z_R1` back to `Z_L1 · Z_R1`. Pauli-algebra shadow: by def. -/
theorem TODO_emergent_CNOT_image_Z_R1 :
    Code4Code4_CNOT_image_Z_R1
      = (PauliString.mul Code4Code4_Z_L1_left Code4Code4_Z_L1_right).2 := rfl

/-! ### Open: operational emergent-action theorem

    The 4 `TODO_emergent_CNOT_image_*` theorems above hold by `rfl`
    at the Pauli-algebra level. The operational claim — that
    applying the surgery schedule to a quantum state in the joint
    codespace yields the state transformed by logical CNOT —
    remains open pending infrastructure for `LogicalState` and
    `apply_surgery_with_corrections`.

    See [gaps/qianxu-G-Phase-B.md](../../../gaps/qianxu-G-Phase-B.md)
    "What is NOT closed at this layer" for the formal scope of the
    open direction.

    What Iter 140 contributes: the **conjugation-rule images** are
    now defined and decide-witnessed (X_L1 → X_L1·X_R1, X_R1
    unchanged, Z_L1 unchanged, Z_R1 → Z_L1·Z_R1), establishing the
    target Pauli-algebra shape that the operational theorem must
    deliver. Future work fills in the operational machinery. -/

end FormalRV.BQCode
